# Generated by Django 5.1.3 on 2024-12-18 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('image', models.ImageField(blank=True, null=True, upload_to='employee_images/')),
                ('name', models.CharField(max_length=100)),
                ('mobile', models.CharField(max_length=15)),
                ('designation', models.CharField(max_length=100)),
                ('gender', models.CharField(max_length=10)),
                ('course', models.CharField(max_length=100)),
                ('createdate', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
