# Generated by Django 5.1.3 on 2024-12-18 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='email',
            field=models.EmailField(default='none@gmail.com', max_length=254, unique=True),
        ),
    ]
